#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Spring_Time.Resource", IsApplication=true)]

namespace Spring_Time
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070000
			public const int TempEntriesPref = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int TempValuesPref = 2131165185;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int activity_horizontal_margin = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int activity_vertical_margin = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int list_item_min_height = 2131034114;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int sw_icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09000a
			public const int action_location = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int action_settings = 2131296267;
			
			// aapt resource value: 0x7f09000c
			public const int action_share = 2131296268;
			
			// aapt resource value: 0x7f090000
			public const int container = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int detailsTextView = 2131296257;
			
			// aapt resource value: 0x7f090006
			public const int linearLayout1 = 2131296262;
			
			// aapt resource value: 0x7f090005
			public const int listItemDateTextView = 2131296261;
			
			// aapt resource value: 0x7f090004
			public const int listItemForecastTextView = 2131296260;
			
			// aapt resource value: 0x7f090007
			public const int listItemHighTextView = 2131296263;
			
			// aapt resource value: 0x7f090002
			public const int listItemIcon = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int listItemLayoutDay = 2131296259;
			
			// aapt resource value: 0x7f090008
			public const int listItemLowTextView = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int listViewForecast = 2131296265;
			
			// aapt resource value: 0x7f09000d
			public const int refresh_weather = 2131296269;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ActivityDetail = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DetailFragment = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ListItemLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ListItemTodayLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MainFragment = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int DetailMenu = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int ForecastFragmentMenu = 2131230721;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060010
			public const int FormatTemperature = 2131099664;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			// aapt resource value: 0x7f060009
			public const int LocationPrefDefault = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int LocationPrefKey = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int LocationPrefLabel = 2131099655;
			
			// aapt resource value: 0x7f060003
			public const int OpenWeatherKey = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int Refresh = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int Settings = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int ShareWeather = 2131099654;
			
			// aapt resource value: 0x7f06000d
			public const int TempPrefDefault = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int TempPrefDialogTitle = 2131099660;
			
			// aapt resource value: 0x7f06000f
			public const int TempPrefImperial = 2131099663;
			
			// aapt resource value: 0x7f06000a
			public const int TempPrefKey = 2131099658;
			
			// aapt resource value: 0x7f06000e
			public const int TempPrefMetric = 2131099662;
			
			// aapt resource value: 0x7f06000b
			public const int TempPrefTitle = 2131099659;
			
			// aapt resource value: 0x7f060005
			public const int ViewLocation = 2131099653;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int GeneralPreference = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
